site:
  title: "Dr Dayyanah Sumodhee"
  baseline: ""
  baseurl: "/"
  canonicalurl: true
  description: "Professional Website of Dr Dayyanah Sumodhee"
  pagination:
    max: 5
    path: "page"
  date:
    format: "j F Y"
    timezone: "Europe/London"
  netlify:
    cms:
      path: "admin"
      version: "latest"
    identity:
      version: "v1"
  output:
    formats:
      netlify_redirects:
        mediatype: "text/plain"
        extension: ""
  virtualpages:
    admin:
      layout: admin/index
      output: html
      title: "Content Manager (Netlify CMS)"
    home:
      redirect: /
    _redirects:
      output: netlify_redirects
theme: "hyde"
